CMS::Group broken association
I don't understand why was this ever here. But it presently cannot work
because target class of this association cannot be discovered by Rails.
I consider that it is used from nowhere and can be safely removed.

```
[86] pry(main)> CMS::Group.joins(:tenant).to_sql
NameError: uninitialized constant CMS::Group::Tenant
from /home/avalon/.asdf/installs/ruby/2.7.8/lib/ruby/gems/2.7.0/gems/activerecord-6.1.7.8/lib/active_record/inheritance.rb:237:in `compute_type'
```