Skip the test using fibers
This test caused multiple tests fail with:
```
ThreadError: deadlock; lock already owned by another fiber belonging to the same thread
```

This is fixed in Rails 7.0.6 and higher: https://github.com/rails/rails/pull/46553