Remove default scope for Invoice to avoid ORDER BY not working in Oracle
The error is:
OCIError: ORA-00907: missing right parenthesis

The code that generates the query is:
PaymentIntent.by_invoice(provider_account.buyer_invoices).find_by!(reference: payment_intent_id)
and it appears in Finance::StripePaymentIntentUpdateService

Pure Oracle query that causes the error:

SELECT "PAYMENT_INTENTS".* FROM "PAYMENT_INTENTS" WHERE "PAYMENT_INTENTS"."INVOICE_ID" IN (SELECT "INVOICES"."ID" FROM "INVOICES" WHERE "INVOICES"."PROVIDER_ACCOUNT_ID" =  41 ORDER BY invoices.created_at DESC) AND "PAYMENT_INTENTS"."REFERENCE" = "payment-intent-1" AND ROWNUM <= 1;

Apparently, ORDER BY in a subquery used for IN clause is unsupported by
Oracle.